box/urls.py
from django.urls import path
from .views import HomePage, update_profile, event_detail, events_list,events_management,edit_event,create_event,delete_event,event_registration_confirmation, already_registered, my_events, register_event
app_name = "box"

urlpatterns = [
    path('', HomePage, name='home'),
    path("accounts/profile/", update_profile, name='profile'),
    path("events/", events_list, name='events_list'),
    path("events/<int:event_id>/detail/", event_detail, name='event_detail'),
    path('manage-events/', events_management, name='manage_events'),
    path('edit-event/<int:event_id>/', edit_event, name='edit_event'),
    path('create-event/', create_event, name='create_event'),
    path('delete-event/<int:event_id>/', delete_event, name='delete_event'),
    path('register-event/<int:event_id>/', register_event, name='register_event'),
    path('events/<int:event_id>/register/confirmation/', event_registration_confirmation, name='event_registration_confirmation'),
    path('already-registered', already_registered, name='already_registered'),
    path('my-events', my_events, name='my_events'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("box.urls",namespace="box")),
    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

box/models.py
from django.db import models
from django.contrib.auth.admin import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import Group, Permission
from datetime import date

def create_organiser_group():
    organiser_group, created = Group.objects.get_or_create(name='organiser')
    if created:
        organiser_group.permissions.set([
            Permission.objects.get(codename='add_event'),
            Permission.objects.get(codename='change_event'),
            Permission.objects.get(codename='delete_event'),
        ])
create_organiser_group()


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(null=True, blank=True)
    nickname = models.CharField(max_length=100, null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    profile_picture = models.ImageField(null=True, blank=True, upload_to="images/")
    not_matched_counter = models.IntegerField(default= 0)
    BOXER_TYPE_CHOICES = [
        ('amateur','Amateur'),
        ('professional','Professional'),
    ]
    boxer_type = models.CharField(max_length=20, choices=BOXER_TYPE_CHOICES, default='amateur')
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)


    def __str__(self):
        return self.user.username
    
    def is_organiser(self):
        return self.user.groups.filter(name='organiser').exists()
    
    @property
    def is_registered_for_event(self):
        return EventRegistration.objects.filter(user=self.user, matched=True).exists()    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


class BoxingEvent(models.Model):
    title = models.CharField(max_length=225, null=True)
    date = models.DateField()
    location = models.CharField(max_length=255)
    registered_users = models.ManyToManyField(User, through='EventRegistration')
    fights = models.ManyToManyField('Fight', through='EventFight')

    def __str__(self):
        return f"{self.title} - {self.date} - {self.location}"
    
    def is_event_completed(self):
        return date.today() >= self.date
    
    def get_date(self):
        return self.date

class Fight(models.Model):
    red_boxer = models.ForeignKey(User, related_name='red_boxer', on_delete=models.CASCADE)
    blue_boxer = models.ForeignKey(User, related_name='blue_boxer', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.red_boxer.username} vs {self.blue_boxer.username}"

class EventFight(models.Model):
    event = models.ForeignKey(BoxingEvent, on_delete=models.CASCADE)
    fight = models.ForeignKey(Fight, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null= True, blank= True)
    red_boxer_result = models.CharField(max_length= 10, blank = True, null = True, choices=[('win','Win'),('loss','Loss'),('draw','Draw')])
    blue_boxer_result = models.CharField(max_length= 10, blank = True, null = True, choices=[('win','Win'),('loss','Loss'),('draw','Draw')])


    class Meta:
        unique_together = ('event', 'order')
        ordering = ['order']
    
    def __str__(self):
        return f"{self.event} - {self.fight} - Order: {self.order}"

class EventRegistration(models.Model):
    user = models.ForeignKey(User,null =True, on_delete=models.CASCADE)
    event = models.ForeignKey(BoxingEvent, on_delete=models.CASCADE)
    registered = models.BooleanField(default= False)
    matched = models.BooleanField(default= False)
    

    def __str__(self):
        return f"{self.user.username} registered for {self.event}"

box/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile,BoxingEvent

class UserForm(forms.ModelForm):
    email = forms.EmailField
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("age", "nickname", "weight", "profile_picture", "boxer_type", "gender")
        widgets = {
            'weight': forms.NumberInput(attrs={'step': 'any'}),  # Allow any decimal value
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['weight'].required = True 
        self.fields['age'].required = True 
        self.fields['gender'].required = True 

class EventForm(forms.ModelForm):
    class Meta:
        model = BoxingEvent
        fields = ("title", "date", "location")

box/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserForm, UserProfileForm, EventForm
from .models import UserProfile, BoxingEvent, EventRegistration, EventFight, Fight
from .helper import update_not_matched_counters, reset_user_not_matched_counter, calculate_points
import datetime


def HomePage(request):
    return render(request,'box/home.html')

@login_required
@transaction.atomic
def update_profile(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    user_form = UserForm(request.POST or None, instance=request.user)
    profile_form = UserProfileForm(request.POST or None, request.FILES or None, instance=user_profile)

    if request.method == 'POST':
        if user_form.is_valid() and profile_form.is_valid():
            try:
                user_form.save()
                profile_form.save()
                messages.success(request, "Profile updated successfully.")
                return redirect('box:profile')
            except Exception as e:
                messages.error(request, f"An error occurred. Please try again. {str(e)}")

    return render(request, 'box/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'user': request.user,
        'user_profile': user_profile
    })

@login_required
def events_list(request):
    today = datetime.date.today()
    events = BoxingEvent.objects.filter(date__gte=today)
    return render(request, 'box/events_list.html', {'events': events})

def event_detail(request, event_id):
    event = get_object_or_404(BoxingEvent, id=event_id)
    registrations = EventRegistration.objects.filter(event=event)

    one_day_before_event = datetime.date.today() >= (event.date - datetime.timedelta(days=1))
    context = {
        'event': event,
        'registrations': registrations,
        'one_day_before_event': one_day_before_event,
    }
    return render(request, 'box/event_detail.html', context)

@login_required
def event_registration_confirmation(request, event_id):
    event = get_object_or_404(BoxingEvent, id=event_id)
    registration = EventRegistration(user=request.user, event=event)
    if EventRegistration.objects.filter(user=request.user, event=event, registered=True).exists():
        return redirect('box:already_registered')
    registration.registered = True
    registration.save()
    return render(request, 'box/event_registration_confirmation.html', {'event': event})

def register_event(request, event_id):
    event = get_object_or_404(BoxingEvent, id=event_id)
    user_profile = UserProfile.objects.get_or_create(user=request.user)[0]
    registration = EventRegistration(user=request.user, event=event)
    
    max_fights = 6
    current_fights_count = EventFight.objects.filter(event=event).count()
    if current_fights_count >= max_fights:
        messages.error(request, "The maximum number of fights has been reached for this event.")
        return redirect('box:events_list')

    if request.method == "POST":
        profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        matches = find_matches(request.user, event)
        if matches:
            create_fight(matches, event)
            update_not_matched_counters(event)
            return redirect('box:event_detail', event_id=event.id)
        return redirect('box:events_list')
    else:
        profile_form = UserProfileForm(instance=user_profile)
   
    return redirect('box:event_detail', event_id=event.id)
def already_registered(request):
    return render(request, 'box/already_registered.html')

def find_matches(current_user, event):
    weight_classes_amateurs_male = {}
    weight_classes_professionals_male = {}
    weight_classes_amateurs_female = {}
    weight_classes_professionals_female = {}

    for user_registration in EventRegistration.objects.filter(event=event, matched=False):
        user = user_registration.user
        weight = int(user.userprofile.weight)
        weight_class = (weight // 1)
        if user.userprofile.gender == 'M':
            weight_classes = weight_classes_amateurs_male if user.userprofile.boxer_type == 'amateur' else weight_classes_professionals_male
        elif user.userprofile.gender == 'F':
            weight_classes = weight_classes_amateurs_female if user.userprofile.boxer_type == 'amateur' else weight_classes_professionals_female
        else:
            continue
    
        if weight_class not in weight_classes:
            weight_classes[weight_class] = []
        weight_classes[weight_class].append(user)

    for weight_classes in [weight_classes_amateurs_male, weight_classes_professionals_male, weight_classes_amateurs_female, weight_classes_professionals_female]:
        for users in weight_classes.values():
            users.sort(key = lambda user: (user.userprofile.not_matched_counter, calculate_points(user.userprofile)), reverse= True)

    matches = []
    matched_users = set()
    max_fights_per_class = 6

    for weight_classes in [weight_classes_amateurs_male, weight_classes_professionals_male, weight_classes_amateurs_female, weight_classes_professionals_female]:
        for weight_class, users in sorted(weight_classes.items(), reverse= True):
            fights_created = 0
            for i in range(len(users)):
                user1 = users[i]
                if user1 in matched_users or fights_created == max_fights_per_class:
                    continue
                for j in range(i+1, len(users)):
                    user2 = users[j]
                    if user2 in matched_users or user1 in matched_users or user1 == user2:
                        continue
                    if calculate_points(user1.userprofile) == 0:
                        if calculate_points(user2.userprofile) == 0:
                            matches.append((user1, user2))
                            matched_users.add(user1)
                            matched_users.add(user2)
                            reset_user_not_matched_counter(user1, event)
                            reset_user_not_matched_counter(user2, event)
                            fights_created += 1
                    points_difference = abs(calculate_points(user1.userprofile) - calculate_points(user2.userprofile))
                    if user1 not in matched_users and user2 not in matched_users and points_difference <= 5 and points_difference >= -5 and calculate_points(user1.userprofile) != 0 and calculate_points(user2.userprofile) != 0:
                        matches.append((user1, user2))
                        matched_users.add(user1)
                        matched_users.add(user2)
                        reset_user_not_matched_counter(user1, event)
                        reset_user_not_matched_counter(user2, event)
                        fights_created += 1
                        break

    return matches


def create_fight(matches, event):
    current_fights_count = EventFight.objects.filter(event=event).count()
    
    for i, (user1, user2) in enumerate(matches):
        order = current_fights_count + i + 1  # Increment the order for the new fight
        fight = Fight.objects.create(red_boxer=user1, blue_boxer=user2)
        event_fight = EventFight.objects.create(event=event, fight=fight, order=order)
    
        registration_user1 = EventRegistration.objects.get(user=user1, event=event)
        registration_user1.matched = True
        registration_user1.save()

        registration_user2 = EventRegistration.objects.get(user=user2, event=event)
        registration_user2.matched = True
        registration_user2.save()
    return event_fight

def events_management(request):
    events = BoxingEvent.objects.all()
    return render(request, 'box/events_management.html', {'events': events})

@login_required
def create_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return redirect('box:manage_events')
    else:
        form = EventForm()
    
    return render(request, 'box/create_event.html', {'form': form})


@login_required
def edit_event(request,event_id):
    event = get_object_or_404(BoxingEvent,id=event_id)
    today = datetime.date.today()
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
        if event.date == today:
            update_match_results(request, event)
            update_user_records_from_results(event, get_event_results(request,event))
        return redirect('box:manage_events')
    else:
        form = EventForm(instance=event)

    match_results_allowed = (event.date == today)
    one_day_before_event = datetime.date.today() == (event.date - datetime.timedelta(days=1))
    context = {
        'form': form,
        'event': event,
        'match_results_allowed': match_results_allowed,
        'one_day_before_event': one_day_before_event,
    }
        
    return render(request, 'box/edit_event.html', context)


def update_match_results(request, event):
    for event_fight in event.eventfight_set.all():
        red_result = request.POST.get(f"red_result_{event_fight.id}")
        blue_result = request.POST.get(f"blue_result_{event_fight.id}")

        event_fight.red_boxer_result = red_result
        event_fight.blue_boxer_result = blue_result
        event_fight.save()

def delete_event(request, event_id):
    event = get_object_or_404(BoxingEvent,id=event_id)
    event.delete()
    return redirect('box:manage_events')

@login_required
def my_events(request):
    user_registrations = EventRegistration.objects.filter(user=request.user)
    searching_for_opponent =[]
    matched_opponent = []
    event_complete = []
    for registration in user_registrations:

box/templates/box/already_registered.html
<title>Already Registered</title>
{% extends 'box/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'box/css/already_registered.css' %}">

    <div class="container">
        <h1>Already Registered</h1>
        <p>You are already registered for this event.</p>
    </div>
{% endblock %}

box/templates/box/base.html
{% load static %}
    <!-- Your profile page content here -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Link to the Boxicon CSS file-->
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

        <!-- Link to the CSS file -->
        <link rel="stylesheet" type="text/css" href="{% static 'box/css/base.css' %}">
    </head>
    <body>
        <div class="content-container">
            {% block content %}{% endblock %}
        </div>
        <nav>
            <div class="logo">
                <i class='bx bx-menu menu-icon'></i>
                <span class="logo-name">Boxing Promotions</span>
            </div>
            <div class="sidebar">
                <div class="logo">
                    <i class='bx bx-menu menu-icon'></i>
                    <span class="logo-name">Boxing Promotions</span>
                </div>

                <div class="sidebar-content">
                    <ul class="lists">
                        <li class="list">
                            <a href="{% url 'box:profile' %}" class="nav-link">
                                <i class='bx bxs-user-circle icon'></i>
                                <span class="link">Profile</span>
                            </a>
                        </li>
                        <li class="list">
                            <a href="{% url 'box:events_list' %}" class="nav-link">
                                <i class='bx bxs-calendar-event icon'></i>
                                <span class="link">Event</span>
                            </a>
                        </li>
                        <li class="list">
                            <a href="{% url 'box:my_events' %}" class="nav-link">
                                <i class='bx bxs-calendar icon' ></i>
                                <span class="link">My Event</span>
                            </a>
                        </li>
                    </ul>

                    <div class="bottom-content">
                        <li class="list">
                            <a href="{% url 'account_logout' %}" class="nav-link">
                                <i class='bx bxs-log-out icon'></i>
                                <span class="link">Logout</span>
                            </a>
                        </li>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container messages">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">
                        <span class="close-button" onclick="closeMessage(this)">×</span>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <section class="overlay"></section>

        <script>
            const navBar = document.querySelector("nav"),
                menuBtns = document.querySelectorAll(".menu-icon"),
                overlay = document.querySelector(".overlay");
            
            menuBtns.forEach((menuBtn) => {
                menuBtn.addEventListener("click", () => {
                    navBar.classList.toggle("open");
                });
            });

            overlay.addEventListener("click", () => {
                navBar.classList.remove("open");
            })
        </script>

        <script>
            function closeMessage(element) {
                element.parentElement.style.display = "none";
            }
        </script>
    </body>
</html>

box/templates/box/create_event.html
<title>Create Event</title>

{% extends 'box/base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'box/css/create_event.css' %}">
  <div class="create-event-container">
    <h2>Create Event</h2>

    <form method="post" action="{% url 'box:create_event' %}" class="event-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="create-event-button">Create Event</button>
    </form>
  </div>
{% endblock %}

box/templates/box/edit_event.html
<title>Edit Event</title>

{% extends 'box/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'box/css/edit_event.css' %}">
<div class="edit-event-container">
    <h2>Edit Event</h2>

    <form method="post" action="{% url 'box:edit_event' event_id=event.id %}" id="eventForm">
        {% csrf_token %}
        {{ form.as_p }}

        {% if match_results_allowed %}
        <!-- Add match result input fields for each fight -->
        {% for event_fight in event.eventfight_set.all %}
        <div class="match-result">
            <label for="red_result_{{ event_fight.id }}">Result for {{ event_fight.fight.red_boxer.username }}:</label>
            <select name="red_result_{{ event_fight.id }}">
                <option value="" {% if event_fight.red_boxer_result == '' %}selected{% endif %}>Select</option>
                <option value="win" {% if event_fight.red_boxer_result == 'win' %}selected{% endif %}>Win</option>
                <option value="loss" {% if event_fight.red_boxer_result == 'loss' %}selected{% endif %}>Loss</option>
                <option value="draw" {% if event_fight.red_boxer_result == 'draw' %}selected{% endif %}>Draw</option>
            </select><br>

            <label for="blue_result_{{ event_fight.id }}">Result for {{ event_fight.fight.blue_boxer.username }}:</label>
            <select name="blue_result_{{ event_fight.id }}">
                <option value="" {% if event_fight.blue_boxer_result == '' %}selected{% endif %}>Select</option>
                <option value="win" {% if event_fight.blue_boxer_result == 'win' %}selected{% endif %}>Win</option>
                <option value="loss" {% if event_fight.blue_boxer_result == 'loss' %}selected{% endif %}>Loss</option>
                <option value="draw" {% if event_fight.blue_boxer_result == 'draw' %}selected{% endif %}>Draw</option>
            </select><br>
        </div>
        {% endfor %}
        {% endif %}

        <button type="submit" class="update-button">Update Event</button>
    </form>

    {% if not match_results_allowed %}
    <p class="notification">Match results can only be input on the day of the event.</p>
    {% endif %}
    <!-- Show the "Match Boxers" button only if it's one day before the event -->
    {% if one_day_before_event %}
    <form method="post" action="{% url 'box:register_event' event_id=event.id %}">
        {% csrf_token %}
        <button type="submit" class="match-button">Match Boxers</button>
    </form>
    {% endif %}

    <form method="post" action="{% url 'box:delete_event' event_id=event.id %}">
        {% csrf_token %}
        <button type="submit" class="delete-button">Delete Event</button>
    </form>
</div>
{% endblock %}

box/templates/box/event_detail.html
<title>Event Detail</title>

{% extends 'box/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'box/css/event_detail.css' %}">

    <div class="event-details-container">
        <h2>{{ event.date }} - {{ event.location }}</h2>

        <!-- Display all fights for the event -->
        {% if event.fights.all %}
            <ul class="event-fights-list">
                {% for fight in event.fights.all %}
                    <li class="event-fight-item">{{ fight.red_boxer }} VS {{ fight.blue_boxer }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No fights scheduled for this event.</p>
        {% endif %}

        {% if not one_day_before_event %}
            <!-- Register button to find an opponent -->
            <form method="post" action="{% url 'box:event_registration_confirmation' event.id %}">
                {% csrf_token %}
                <button type="submit" class="register-button">Register</button>
            </form>
        {% else %}
            <p class="registration-closed">Registration is closed.</p>
        {% endif %}
    </div>
{% endblock %}

box/templates/box/event_registration_confirmation.html
<title>Confirmation</title>

{% extends 'box/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'box/css/event_registration_confirmation.css' %}">

    <div class="registration-confirmation-container">
        <h2>Registration Confirmation</h2>

        <p>You have successfully registered for the event on {{ event.date }} at {{ event.location }}.</p>
        <p>We are now finding an opponent for you. Please check back later for more details.</p>
    </div>
{% endblock %}

box/templates/box/events_list.html
<title>Events</title>

{% extends 'box/base.html' %}
{% load static custom_filters %}

{% block title %}Upcoming Boxing Events{% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'box/css/events_list.css' %}">
    <div style="margin-top: 30px;"></div>
    <div class="event-header-container">
        <h2>Upcoming Boxing Events</h2>
    </div>
    
    <div class="event-buttons" style="margin-top: -40px;">
        {% if user|has_group:"organiser" %}
            <a href="{% url 'box:manage_events' %}" style="color: white;">Manage Events</a>
        {% endif %}
    </div>
    {% if user|has_group:"organiser" %}
        {% if events %}
            <ul class="event-fights-list">
                {% for event in events %}
                    <li class="event-box">
                        <h3>{{ event.title }} - {{ event.date }} - {{ event.location }}</h3>
                        <a href="{% url 'box:event_detail' event_id=event.id %}">View Details</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No upcoming events at the moment.</p>
        {% endif %}
    {% endif %}
    {% if not user|has_group:"organiser" %}
        {% if events %}
            <ul class="event-fights-list" style="margin-top: 45px;">
                {% for event in events %}
                    <li class="event-box">
                        <h3>{{ event.title }} - {{ event.date }} - {{ event.location }}</h3>
                        <a href="{% url 'box:event_detail' event_id=event.id %}">View Details</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p style="margin-top:40px;">No upcoming events at the moment.</p>
        {% endif %}
    {% endif %}
{% endblock %}

box/templates/box/events_management.html
<title>Manage Events</title>

{% extends 'box/base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'box/css/events_management.css' %}">
  <div class="events-management-container">
      <h2 style="margin-top: 70px;">Manage Events</h2>

      <a class="create-event-button" href="{% url 'box:create_event' %}">Create Event</a>

      <ul class="events-list">
          {% for event in events %}
          <li class="event-item">
              <div class="event-details">
                  <span class="event-title">{{ event.title }}</span>
                  <span class="event-date">Date: {{ event.date }}</span>
                  <span class="event-location">Location: {{ event.location }}</span>
              </div>
              <div class="event-actions">
                  <a href="{% url 'box:edit_event' event_id=event.id %}" class="edit-event-button">Edit</a>
                  <!-- Add a delete button here if needed -->
              </div>
          </li>
          {% endfor %}
      </ul>
  </div>
{% endblock %}

box/templates/box/profile.html
<title>Profile</title>
{% extends 'box/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'box/css/profile.css' %}">
    
    <div class="profile-container">
        <h2>User Profile</h2>

        <!-- Section for displaying details -->
        <div class="profile-details">
            {% if user.first_name or user.last_name %}
                <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</p>
            {% endif %}
            {% if user_profile.age %}
                <p><strong>Age:</strong> {{ user_profile.age }}</p>
            {% endif %}
            {% if user_profile.nickname %}
                <p><strong>Nickname:</strong> {{ user_profile.nickname }}</p>
            {% endif %}
            {% if user_profile.weight %}
                <p><strong>Weight:</strong> {{ user_profile.weight }}kg</p>
            {% endif %}
            {% if user_profile.boxer_type %}
                <p><strong>Boxer Type:</strong> {{ user_profile.get_boxer_type_display }}</p>
            {% endif %}
            {% if user_profile.gender %}
                <p><strong>Gender:</strong> {{ user_profile.get_gender_display }}</p>
            {% endif %}
            {% if user_profile.wins is not None or user_profile.losses is not None or user_profile.draws is not None %}
                <p><strong>Record:</strong> {{ user_profile.wins|default:0 }}-{{ user_profile.losses|default:0 }}-{{ user_profile.draws|default:0 }}</p>
            {% endif %}
            {% if user_profile.profile_picture %}
                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
            {% endif %}
        </div>

        <!-- Section for the form -->
        <div class="profile-form">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <button type="submit">Update Profile</button>
            </form>
        </div>
    </div>
{% endblock %}